export const loginConstant = {
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCESS: "LOGIN_SUCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",
	LOGOUT_REQUEST: "LOGOUT_REQUEST",
	LOGOUT_SUCESS: "LOGOUT_SUCESS",
	LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const signupConstant = {
	SIGNUP_REQUEST: "SIGNUP_REQUEST",
	SIGNUP_SUCESS: "SIGNUP_SUCESS",
	SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const categoryConstant = {
	CATEGORY_REQUEST: "CATEGORY_REQUEST",
	CATEGORY_SUCESS: "CATEGORY_SUCESS",
	CATEGORY_FAILURE: "CATEGORY_FAILURE",
};

export const productConstant = {
	PRODUCT_REQUEST: "PRODUCT_REQUEST",
	PRODUCT_SUCESS: "PRODUCT_SUCESS",
	PRODUCT_FAILURE: "PRODUCT_FAILURE",
};

export const orderConstant = {
	ORDER_REQUEST: "ORDER_REQUEST",
	ORDER_SUCESS: "ORDER_SUCESS",
	ORDER_FAILURE: "ORDER_FAILURE",
};
